[general]
library_name = "onnxruntime"
output_file_path = "./LibOnnxRuntime.jl"
module_name = "LibOnnxRuntime"
prologue_file_path = "./prologue.jl"
output_ignorelist = ["ORT_API_CALL", "ORTCHAR_T"]
